// Result types and constructors
export {
  type Result,
  type ResultObject,
  type Ok,
  type Err,
  type ChainResult,
  type ResultMatchHandlers,
  type FetchError,
  HttpError,
  NetworkError,
  ParseError,
  ValidationError,
  isHttpError,
  isNetworkError,
  isParseError,
  isValidationError,
  ok,
  err,
  chainResult,
} from "./result.js";

// HTTP client functions
export {
  get,
  post,
  put,
  patch,
  httpRequest,
  getJson,
  postJson,
  putJson,
  patchJson,
  del,
  delAs,
  delVoid,
  getText,
  head,
  createClient,
  http,
  type Schema,
  type RequestOptions,
  type JsonRequestOptions,
  type FetchSafeFetch,
  type RequestHook,
  type ResponseHook,
  type HttpRequestOptions,
  type HttpJsonRequestOptions,
  type ModeResult,
  type ResponseMode,
  type ClientHeaders,
  type ClientOptions,
  type FetchSafeClient,
} from "./client.js";
